name: vggec
channels:
  - defaults
dependencies:
  - jupyter=1.0.0
  - pip=18.1
  - python=3.6.7
  - tensorflow-gpu=1.12.0
  - scikit-learn=0.20.0
  - pip:
    - pysoundfile==0.9.0.post1
    - resampy==0.2.1
